CREATE OR REPLACE VIEW tech_info.activity
AS SELECT a.datid,
    a.datname,
    a.pid,
    a.leader_pid,
    a.usesysid,
    a.usename,
    a.application_name,
    a.client_addr,
    a.client_hostname,
    a.client_port,
    a.backend_start,
    a.xact_start,
    a.query_start,
    a.state_change,
    a.wait_event_type,
    a.wait_event,
    a.state,
    a.backend_xid,
    a.backend_xmin,
    a.query_id,
    a.query,
    a.backend_type
   FROM pg_stat_activity a;